### ISSUE TITLE
Erstellen des Moduls zur Berechnung der Stangenpositionen

### ISSUE THREAD

**Issue by philip-baumgartner** [LukasVoeller/SWE_2017_KickIT#1]
Es soll ein Modul erstellt werden, welches eine Methode newBallPosition(vec2) anbietet. Diese wird durch das Ballerkennungsmodul laufend aufgerufen und sie bekommt die aktuelle Position des Balles als Übergabeparameter. Aus dieser Information sollen die erforderlichen Positionen aller Stangen berechnet werden.

**Comment by LukasVoeller** [comment]
Kann geschlossen werden.
