### ISSUE TITLE
Erstellen eines virtuellen Kickers zum Testen der Berechnung der Stangenpositionen

### ISSUE THREAD

**Issue by philip-baumgartner** [LukasVoeller/SWE_2017_KickIT#2]
Um das Modul #1 ausserhalb der Laborumgebung testen zu können, könnten wir einen virtuellen Kickertisch in c++ erstellen. Der müsste eine Spielfeldumrandung und alle Stangen, als einfache Linien, und alle Spieler, als einfache Punkte besitzen. Der Ball kann durch den Mauszeiger simuliert werden. Sobald sich die Position des Mauszeigers ändert, wird die Methode `newBallPosition()` von #1 aufgerufen.
Anbieten sollte es die Funktion `setRowPosition(int rowNumber, int position)`

**Comment by LukasVoeller** [comment]
Kann geschlossen werden.
